/*
 * File:
 * Author: Qiming Sun <osirpt.sun@gmail.com>
 * Description: code generated by  gen-code.cl
 */
#include "cint_bas.h"
#include "cart2sph.h"
#include "g2e.h"
#include "cint1e.h"
#include "cint2e.h"
#include "misc.h"
#include "fblas.h"
#include "c2f.h"
/* <k i|GAUNT |SIGMA DOT P j SIGMA DOT P l> : i,jin electron 1; k,lin electron 2
 * = (i SIGMA DOT P j|GAUNT |k SIGMA DOT P l) */
static void gout2e_cint2e_ssp1ssp2(double *g, const int *ng,
double *gout, const int nf, const int *idx,
const double ai, const double aj, const double ak, const double al,
const int *shls, const int *atm, const int *bas, const double *env) {
const int INC1 = 1;
const double D1 = 1;
const int i_sh = shls[0];
const int j_sh = shls[1];
const int k_sh = shls[2];
const int l_sh = shls[3];
const int i_l = bas(ANG_OF, i_sh);
const int j_l = bas(ANG_OF, j_sh);
const int k_l = bas(ANG_OF, k_sh);
const int l_l = bas(ANG_OF, l_sh);
const int *idy = idx + nf;
const int *idz = idx + nf * 2;
const double *ri = env + atm(PTR_COORD, bas(ATOM_OF, i_sh));
const double *rj = env + atm(PTR_COORD, bas(ATOM_OF, j_sh));
const double *rk = env + atm(PTR_COORD, bas(ATOM_OF, k_sh));
const double *rl = env + atm(PTR_COORD, bas(ATOM_OF, l_sh));
int ix, iy, iz, i, n;
double *g0 = g;
double *g1 = g0 + g_size(ng) * 3;
double *g2 = g1 + g_size(ng) * 3;
double *g3 = g2 + g_size(ng) * 3;
double *g4 = g3 + g_size(ng) * 3;
double s[9];
G2E_D_L(g1, g0, i_l+0, j_l+1, k_l+0, l_l+0);
G2E_D_J(g2, g0, i_l+0, j_l+0, k_l, l_l);
G2E_D_J(g3, g1, i_l+0, j_l+0, k_l, l_l);
for (n = 0; n < nf; n++) {
ix = idx[n];
iy = idy[n];
iz = idz[n];
dset0(9, s);
for (i = 0; i < ng[RYS_ROOTS]; i++) {
s[0] += g3[ix+i] * g0[iy+i] * g0[iz+i];
s[1] += g2[ix+i] * g1[iy+i] * g0[iz+i];
s[2] += g2[ix+i] * g0[iy+i] * g1[iz+i];
s[3] += g1[ix+i] * g2[iy+i] * g0[iz+i];
s[4] += g0[ix+i] * g3[iy+i] * g0[iz+i];
s[5] += g0[ix+i] * g2[iy+i] * g1[iz+i];
s[6] += g1[ix+i] * g0[iy+i] * g2[iz+i];
s[7] += g0[ix+i] * g1[iy+i] * g2[iz+i];
s[8] += g0[ix+i] * g0[iy+i] * g3[iz+i];
}
gout[0] = + (1*s[8]) + (1*s[4]);
gout[1] = + (-1*s[1]);
gout[2] = + (-1*s[2]);
gout[3] = + (1*s[5]) + (-1*s[7]);
gout[4] = + (-1*s[3]);
gout[5] = + (1*s[8]) + (1*s[0]);
gout[6] = + (-1*s[5]);
gout[7] = + (-1*s[2]) + (1*s[6]);
gout[8] = + (-1*s[6]);
gout[9] = + (-1*s[7]);
gout[10] = + (1*s[4]) + (1*s[0]);
gout[11] = + (1*s[1]) + (-1*s[3]);
gout[12] = + (1*s[7]) + (-1*s[5]);
gout[13] = + (-1*s[6]) + (1*s[2]);
gout[14] = + (1*s[3]) + (-1*s[1]);
gout[15] = + (1*s[0]) + (1*s[4]) + (1*s[8]);
gout += 16;
}}
int cint2e_ssp1ssp2(double *opkijl, const int *shls,
const int *atm, const int natm,
const int *bas, const int nbas, const double *env) {
const int i_sh = shls[0];
const int j_sh = shls[1];
const int k_sh = shls[2];
const int l_sh = shls[3];
const int i_l = bas(ANG_OF, i_sh);
const int j_l = bas(ANG_OF, j_sh);
const int k_l = bas(ANG_OF, k_sh);
const int l_l = bas(ANG_OF, l_sh);
int ng[] = {1, 1, 1, 1, 1, 1, 1, 1, 1};
ng[3] = j_l + 1 + 1;
ng[2] = l_l + 1 + 1;
ng[1] = k_l + 0 + ng[2];
ng[0] = i_l + 0 + ng[3];
ng[GSHIFT] = 2;
ng[POS_E1] = 4;
ng[POS_E2] = 4;
ng[TENSOR] = 1;
return cint2e_drv(opkijl, ng, 1,
gout2e_cint2e_ssp1ssp2, &c2s_si_2e1i, &c2s_si_2e2i,
shls, atm, natm, bas, nbas, env); }
C2F_(cint2e_ssp1ssp2)
